In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install requests

Requirement already satisfied: requests in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests) (2026.5.20)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []

start_year = datetime.now().year - 5
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):

        start_date = f"{year}-{month:02d}-01"

        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)

        if response.status_code != 200:
            print(f"Failed for {start_date}")
            continue

        data = response.json()

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]

            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),

                "latitude": g[1] if len(g) > 1 else None,
                "longitude": g[0] if len(g) > 0 else None,
                "depth_km": g[2] if len(g) > 2 else None,

                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place": p.get("place"),
                "status": p.get("status"),
                "tsunami": p.get("tsunami"),
                "sig": p.get("sig"),
                "mmi": p.get("mmi"),
                "alert": p.get("alert"),
                "felt": p.get("felt"),
                "cdi": p.get("cdi"),

                "net": p.get("net"),
                "code": p.get("code"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "types": p.get("types"),

                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "type": p.get("type")
            })

# Create DataFrame
df = pd.DataFrame(all_records)

# Display summary
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Show first 5 rows
print(df.head())

# Show column names
print("\nColumns:")
print(df.columns.tolist())

Rows: 117374
Columns: 26
           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...  net  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   us
1                                        Fiji region  reviewed  ...   us
2                    103 km SW of Basco, Philippines  reviewed  ...   us
3                            114 km N of M?n?b, Iran  reviewed  ...   us
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   us

       code           ids sources                                   types  \
0  6000ddi8  ,us6000ddi8,    ,us,  ,dyfi,moment-tensor,origin,phase-data,
1  6000dev6  ,us6000dev6,    ,us,                     ,origin,phase-data,
2  6000dev5  ,us6000dev5,    ,us,                     ,origin,phase-data,
3  6000ddhs  ,us6000ddhs,    ,us,                     ,origin,phase-data,
4  6000dev4  ,us6000dev4,    ,us,                     ,origin,phase-data,

   nst   dmin   rms    gap        type
0  NaN  0.294  0.82   42.0  earthquake
1  NaN  1.471  0.29   64.0  earthquake
2  NaN  3.057  0.69  106.0  earthquake
3  NaN  3.330  0.61   71.0  earthquake
4  NaN  6.023  0.50   65.0  earthquake

[5 rows x 26 columns]

Columns:
['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'sig', 'mmi', 'alert', 'felt', 'cdi', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'type']

In [5]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'mmi', 'alert', 'felt',
       'cdi', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type'],
      dtype='object')

In [6]:
df['place']

0               29 km SW of Villa Basilio Nievas, Argentina
1                                               Fiji region
2                           103 km SW of Basco, Philippines
3                                   114 km N of M?n?b, Iran
4         184 km ENE of Olonkinbyen, Svalbard and Jan Mayen
                                ...
117369                     44 km NW of Te Anau, New Zealand
117370                              57 km E of Mutsu, Japan
117371                         7 km SE of Orosi, Costa Rica
117372                       206 km NW of Oula Xiuma, China
117373                           163 km ENE of Tokār, Sudan
Name: place, Length: 117374, dtype: object

In [7]:
import re

In [8]:
df['country'] = df['place'].apply(lambda x: re.search(r', ([^,]+)$', str(x)).group(1) if re.search(r', ([^,]+)$', str(x)) else str(x).strip())

In [9]:
df[['place','country']]

,place,country
0,"29 km SW of Villa Basilio Nievas, Argentina",Argentina
1,Fiji region,Fiji region
2,"103 km SW of Basco, Philippines",Philippines
3,"114 km N of M?n?b, Iran",Iran
4,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",Svalbard and Jan Mayen
...,...,...
117369,"44 km NW of Te Anau, New Zealand",New Zealand
117370,"57 km E of Mutsu, Japan",Japan
117371,"7 km SE of Orosi, Costa Rica",Costa Rica
117372,"206 km NW of Oula Xiuma, China",China
117373,"163 km ENE of Tokār, Sudan",Sudan

In [10]:
df.describe(include='all')

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,code,ids,sources,types,nst,dmin,rms,gap,type,country
count,117374,117374,117374,117374.000000,117374.000000,117374.000000,117374.000000,117374,117374,117374,...,117374,117374,117374,117374,89612.000000,113399.000000,117355.000000,114352.000000,117374,117374
unique,117374,NaN,NaN,NaN,NaN,NaN,NaN,17,64553,2,...,117374,117374,374,575,NaN,NaN,NaN,NaN,11,531
top,us6000thdb,NaN,NaN,NaN,NaN,NaN,NaN,mb,South Sandwich Islands region,reviewed,...,6000thdb,",us6000thdb,",",us,",",origin,phase-data,",NaN,NaN,NaN,NaN,earthquake,Alaska
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,83145,3178,117207,...,1,1,85434,89251,NaN,NaN,NaN,NaN,116480,14501
mean,NaN,2023-10-24 04:55:24.626970112,2024-02-09 14:34:31.537153536,12.221880,7.751439,71.618216,4.255746,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,45.484556,3.190736,0.658833,122.763247,NaN,NaN
min,NaN,2021-01-01 00:14:07.580000,2021-01-01 10:15:32.601000,-84.493200,-179.999700,-3.740000,3.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,8.000000,NaN,NaN
25%,NaN,2022-05-08 00:07:18.722249984,2022-08-28 03:20:29.289999872,-14.330375,-112.127000,10.000000,4.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.000000,0.834100,0.490000,75.000000,NaN,NaN
50%,NaN,2023-10-31 20:01:40.632999936,2024-02-10 23:47:33.040000,14.920400,25.128300,21.538000,4.300000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,32.000000,1.813000,0.650000,113.000000,NaN,NaN
75%,NaN,2025-04-23 16:17:10.148499968,2025-08-20 22:30:48.630249984,39.168750,130.593000,70.842750,4.600000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,56.000000,3.730000,0.820000,157.000000,NaN,NaN
max,NaN,2026-08-14 18:33:25.499000,2026-08-14 19:14:01.617000,87.375200,179.999400,683.578000,8.800000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,619.000000,62.558000,3.400000,359.000000,NaN,NaN
std,NaN,NaN,NaN,31.958876,129.039306,122.981693,0.610602,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39.516576,4.461846,0.259028,62.922292,NaN,NaN

In [11]:
df.select_dtypes(include='object').values.T

array([['us6000ddi8', 'us6000dev6', 'us6000dev5', ..., 'us6000thdg',
        'us6000thdc', 'us6000thdb'],
       ['mwr', 'mb', 'mb', ..., 'mb', 'mb', 'mb'],
       ['29 km SW of Villa Basilio Nievas, Argentina', 'Fiji region',
        '103 km SW of Basco, Philippines', ...,
        '7 km SE of Orosi, Costa Rica', '206 km NW of Oula Xiuma, China',
        '163 km ENE of Tokār, Sudan'],
       ...,
       [',dyfi,moment-tensor,origin,phase-data,', ',origin,phase-data,',
        ',origin,phase-data,', ..., ',dyfi,origin,phase-data,',
        ',origin,phase-data,', ',origin,phase-data,'],
       ['earthquake', 'earthquake', 'earthquake', ..., 'earthquake',
        'earthquake', 'earthquake'],
       ['Argentina', 'Fiji region', 'Philippines', ..., 'Costa Rica',
        'China', 'Sudan']], shape=(12, 117374), dtype=object)

In [12]:
print(df.head())

           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...      code  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...  6000ddi8
1                                        Fiji region  reviewed  ...  6000dev6
2                    103 km SW of Basco, Philippines  reviewed  ...  6000dev5
3                            114 km N of M?n?b, Iran  reviewed  ...  6000ddhs
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...  6000dev4

            ids  sources                                   types  nst   dmin  \
0  ,us6000ddi8,     ,us,  ,dyfi,moment-tensor,origin,phase-data,  NaN  0.294
1  ,us6000dev6,     ,us,                     ,origin,phase-data,  NaN  1.471
2  ,us6000dev5,     ,us,                     ,origin,phase-data,  NaN  3.057
3  ,us6000ddhs,     ,us,                     ,origin,phase-data,  NaN  3.330
4  ,us6000dev4,     ,us,                     ,origin,phase-data,  NaN  6.023

    rms    gap        type                 country
0  0.82   42.0  earthquake               Argentina
1  0.29   64.0  earthquake             Fiji region
2  0.69  106.0  earthquake             Philippines
3  0.61   71.0  earthquake                    Iran
4  0.50   65.0  earthquake  Svalbard and Jan Mayen

[5 rows x 27 columns]

In [13]:
if 'alert' in df.columns:
    df['alert'] = df['alert'].astype(str).str.lower().replace('nan', pd.NA)
    string_cols = ['magType', 'status', 'type', 'net', 'sources', 'types']
for col in string_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).fillna('').str.strip().str.lower()

In [14]:
df[string_cols].dtypes

magType    object
status     object
type       object
net        object
sources    object
types      object
dtype: object

In [15]:
df['alert'].isna().sum()

np.int64(0)

In [16]:
df.isna().sum()

id                0
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag               0
magType           0
place             0
status            0
tsunami           0
sig               0
mmi          107106
alert             0
felt          99447
cdi           99447
net               0
code              0
ids               0
sources           0
types             0
nst           27762
dmin           3975
rms              19
gap            3022
type              0
country           0
dtype: int64

In [17]:
df[['nst','dmin', 'rms', 'gap', 'mmi', 'felt', 'cdi']].isna().sum()

nst      27762
dmin      3975
rms         19
gap       3022
mmi     107106
felt     99447
cdi      99447
dtype: int64

In [18]:
df['nst'] = pd.to_numeric(df['nst'], errors='coerce')
df['nst'] = df['nst'].fillna(df['nst'].median())
df['mmi'] = pd.to_numeric(df['mmi'], errors='coerce')
df['mmi'] = df['mmi'].fillna(df['mmi'].median())
df['felt'] = pd.to_numeric(df['felt'], errors='coerce')
df['felt'] = df['felt'].fillna(df['felt'].median())
df['cdi'] = pd.to_numeric(df['cdi'], errors='coerce')
df['cdi'] = df['cdi'].fillna(df['cdi'].median())
df['dmin'] = pd.to_numeric(df['dmin'], errors='coerce')
df['dmin'] = df['dmin'].fillna(df['dmin'].median())
df['rms'] = pd.to_numeric(df['rms'], errors='coerce')
df['rms'] = df['rms'].fillna(df['rms'].median())
df['gap'] = pd.to_numeric(df['gap'], errors='coerce')
df['gap'] = df['gap'].fillna(df['gap'].median())

In [19]:
df[['nst','dmin', 'rms', 'gap', 'mmi', 'felt', 'cdi']].isna().sum()

nst     0
dmin    0
rms     0
gap     0
mmi     0
felt    0
cdi     0
dtype: int64

In [20]:
df.isna().sum()

id           0
time         0
updated      0
latitude     0
longitude    0
depth_km     0
mag          0
magType      0
place        0
status       0
tsunami      0
sig          0
mmi          0
alert        0
felt         0
cdi          0
net          0
code         0
ids          0
sources      0
types        0
nst          0
dmin         0
rms          0
gap          0
type         0
country      0
dtype: int64

In [21]:
df['time']

0        2021-01-31 23:20:49.923
1        2021-01-31 23:08:17.161
2        2021-01-31 22:54:19.760
3        2021-01-31 22:06:00.832
4        2021-01-31 21:51:14.016
                   ...
117369   2026-08-01 03:23:55.189
117370   2026-08-01 02:48:01.570
117371   2026-08-01 02:16:27.638
117372   2026-08-01 01:29:36.859
117373   2026-08-01 01:24:09.262
Name: time, Length: 117374, dtype: datetime64[ns]

In [22]:
df['time'].dt.year

0         2021
1         2021
2         2021
3         2021
4         2021
          ...
117369    2026
117370    2026
117371    2026
117372    2026
117373    2026
Name: time, Length: 117374, dtype: int32

In [23]:
df['year'] = df['time'].dt.year

In [24]:
df['time'].dt.month

0         1
1         1
2         1
3         1
4         1
         ..
117369    8
117370    8
117371    8
117372    8
117373    8
Name: time, Length: 117374, dtype: int32

In [25]:
df['month'] = df['time'].dt.month

In [26]:
df['time'].dt.day

0         31
1         31
2         31
3         31
4         31
          ..
117369     1
117370     1
117371     1
117372     1
117373     1
Name: time, Length: 117374, dtype: int32

In [27]:
df['day'] = df['time'].dt.day

In [28]:
df['time'].dt.day_name()

0           Sunday
1           Sunday
2           Sunday
3           Sunday
4           Sunday
            ...
117369    Saturday
117370    Saturday
117371    Saturday
117372    Saturday
117373    Saturday
Name: time, Length: 117374, dtype: object

In [29]:
df['day_of_week'] = df['time'].dt.day_name()

In [30]:
df.shape

(117374, 31)

In [31]:
df.isna().sum()

id             0
time           0
updated        0
latitude       0
longitude      0
depth_km       0
mag            0
magType        0
place          0
status         0
tsunami        0
sig            0
mmi            0
alert          0
felt           0
cdi            0
net            0
code           0
ids            0
sources        0
types          0
nst            0
dmin           0
rms            0
gap            0
type           0
country        0
year           0
month          0
day            0
day_of_week    0
dtype: int64

In [32]:
df['depth_km']

0          17.270
1         426.710
2          46.730
3          10.000
4          10.000
           ...
117369    112.486
117370     82.290
117371     10.000
117372     10.000
117373     10.000
Name: depth_km, Length: 117374, dtype: float64

In [33]:
import numpy as np
np.where(df['depth_km'] < 70, 'shallow', 'deep')

array(['shallow', 'deep', 'shallow', ..., 'shallow', 'shallow', 'shallow'],
      shape=(117374,), dtype='<U7')

In [34]:
df['depth_category'] = np.where(df['depth_km'] < 70, 'shallow', 'deep')

In [35]:
df['depth_category']

0         shallow
1            deep
2         shallow
3         shallow
4         shallow
           ...
117369       deep
117370       deep
117371    shallow
117372    shallow
117373    shallow
Name: depth_category, Length: 117374, dtype: object

In [36]:
df.shape

(117374, 32)

In [37]:
df['mag']

0         4.7
1         4.1
2         4.7
3         4.9
4         4.0
         ...
117369    4.8
117370    5.5
117371    4.3
117372    4.7
117373    4.6
Name: mag, Length: 117374, dtype: float64

In [38]:
conditions = [(df['mag'] >= 6.0) & (df['mag'] < 7.0),(df['mag'] >= 7.0)]
choices = ['Strong', 'Destructive']
df['strong_destructive_flag'] = np.select(conditions, choices, default='Not Strong/Destructive')

In [39]:
df['strong_destructive_flag']

0         Not Strong/Destructive
1         Not Strong/Destructive
2         Not Strong/Destructive
3         Not Strong/Destructive
4         Not Strong/Destructive
                   ...
117369    Not Strong/Destructive
117370    Not Strong/Destructive
117371    Not Strong/Destructive
117372    Not Strong/Destructive
117373    Not Strong/Destructive
Name: strong_destructive_flag, Length: 117374, dtype: object

In [40]:
df.shape

(117374, 33)

In [42]:
df.to_csv("earthquakes_data.csv", index=False)

In [43]:
df=pd.read_csv('earthquakes_data.csv')
df.head(10)

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,rms,gap,type,country,year,month,day,day_of_week,depth_category,strong_destructive_flag
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.70,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,0.82,42.0,earthquake,Argentina,2021,1,31,Sunday,shallow,Not Strong/Destructive
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.10,mb,Fiji region,reviewed,...,0.29,64.0,earthquake,Fiji region,2021,1,31,Sunday,deep,Not Strong/Destructive
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.70,mb,"103 km SW of Basco, Philippines",reviewed,...,0.69,106.0,earthquake,Philippines,2021,1,31,Sunday,shallow,Not Strong/Destructive
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.90,mb,"114 km N of M?n?b, Iran",reviewed,...,0.61,71.0,earthquake,Iran,2021,1,31,Sunday,shallow,Not Strong/Destructive
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.00,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,0.50,65.0,earthquake,Svalbard and Jan Mayen,2021,1,31,Sunday,shallow,Not Strong/Destructive
5,pr2021031019,2021-01-31 21:34:54.690,2021-04-16 19:02:43.040,18.9996,-65.4121,46.00,3.55,md,"76 km NNE of Luquillo, Puerto Rico",reviewed,...,0.31,305.0,earthquake,Puerto Rico,2021,1,31,Sunday,shallow,Not Strong/Destructive
6,pr2021031018,2021-01-31 21:26:30.180,2021-01-31 21:52:15.880,19.0250,-65.4221,30.00,3.27,md,"78 km NNE of Luquillo, Puerto Rico",reviewed,...,0.37,305.0,earthquake,Puerto Rico,2021,1,31,Sunday,shallow,Not Strong/Destructive
7,pr2021031020,2021-01-31 21:14:31.020,2021-04-16 19:02:43.040,19.0436,-65.3590,28.00,3.48,md,"82 km N of Culebra, Puerto Rico",reviewed,...,0.37,309.0,earthquake,Puerto Rico,2021,1,31,Sunday,shallow,Not Strong/Destructive
8,us6000dev3,2021-01-31 20:57:55.804,2021-04-16 19:03:46.040,5.6376,126.7150,18.68,4.30,mb,"99 km SE of Pondaguitan, Philippines",reviewed,...,0.49,139.0,earthquake,Philippines,2021,1,31,Sunday,shallow,Not Strong/Destructive
9,us6000dev2,2021-01-31 20:54:42.248,2021-04-16 19:03:46.040,5.8436,126.5404,75.53,4.20,mb,"69 km SE of Pondaguitan, Philippines",reviewed,...,0.58,196.0,earthquake,Philippines,2021,1,31,Sunday,deep,Not Strong/Destructive

In [44]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pearl\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
from sqlalchemy import create_engine
username='earthquake_user'
password='LV3TUg8gpIuzQaMIjkfIqQqJ80PGePMp'
port=5432
database_name='earthquake_db_cdfc'
host_name='dpg-d9vmeoe417fc73e90tj0-a'
engine=create_engine(f'postgresql+psycopg2://{username}:{password}@{host_name}:{port}/{database_name}')

In [48]:
from sqlalchemy import create_engine

DATABASE_URL = "postgresql://earthquake_user:LV3TUg8gpIuzQaMIjkfIqQqJ80PGePMp@dpg-d9vmeoe417fc73e90tj0-a.oregon-postgres.render.com/earthquake_db_cdfc"

engine = create_engine(DATABASE_URL)

# Test connection
with engine.connect() as connection:
    print("Database connected successfully!")

Database connected successfully!

In [51]:
from sqlalchemy import create_engine

engine.dispose()

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True
)

In [52]:
with engine.connect() as conn:
    print("Database connection successful!")

Database connection successful!

In [53]:
df.to_sql(
    'earthquakes',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=5000,
    method='multi'
)

print("Data uploaded successfully!")

Data uploaded successfully!

In [49]:
df.to_sql('earthquakes', con=engine, if_exists='replace', index=False,chunksize=10000,method='multi')

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)

In [54]:
query = """
SELECT
    id,
    time,
    place,
    country,
    mag,
    depth_km,
    strong_destructive_flag
FROM earthquakes
ORDER BY mag DESC
LIMIT 10;
"""

top10 = pd.read_sql(query, engine)

In [56]:
top10

,id,time,place,country,mag,depth_km,strong_destructive_flag
0,us6000qw60,2025-07-29 23:24:52.483,"2025 Kamchatka Peninsula, Russia Earthquake",Russia Earthquake,8.8,35.000,Destructive
1,ak0219neiszm,2021-07-29 06:15:49.188,"2021 Chignik, Alaska Earthquake",Alaska Earthquake,8.2,35.000,Destructive
2,us6000f53e,2021-08-12 18:35:17.231,2021 South Sandwich Islands Earthquake,2021 South Sandwich Islands Earthquake,8.1,22.790,Destructive
3,us7000dflf,2021-03-04 19:28:33.178,"2021 Kermadec Islands, New Zealand Earthquake",New Zealand Earthquake,8.1,28.930,Destructive
4,us7000srb1,2026-06-07 23:37:41.970,"25 km SW of Kablalan, Philippines",Philippines,7.8,56.991,Destructive
5,us6000jllz,2023-02-06 01:17:34.342,"Pazarcik earthquake, Kahramanmaras earthquake ...",Kahramanmaras earthquake sequence,7.8,10.000,Destructive
6,us7000qx2g,2025-09-18 18:58:14.939,"140 km E of Petropavlovsk-Kamchatsky, Russia",Russia,7.8,27.000,Destructive
7,us7000pn9s,2025-03-28 06:20:52.715,"2025 Mandalay, Burma (Myanmar) Earthquake",Burma (Myanmar) Earthquake,7.7,10.000,Destructive
8,us6000kd0n,2023-05-19 02:57:03.172,southeast of the Loyalty Islands,southeast of the Loyalty Islands,7.7,18.053,Destructive
9,us6000dg77,2021-02-10 13:19:55.530,southeast of the Loyalty Islands,southeast of the Loyalty Islands,7.7,10.000,Destructive

In [57]:
query = """
SELECT
    id,
    time,
    place,
    country,
    depth_km,
    mag
FROM earthquakes
ORDER BY depth_km DESC
LIMIT 10;
"""

top10_deepest = pd.read_sql(query, engine)

In [58]:
top10_deepest

,id,time,place,country,depth_km,mag
0,us6000sp3p,2026-04-02 16:59:17.870,"206 km ENE of Sola, Vanuatu",Vanuatu,683.578,4.0
1,us6000k2db,2023-04-01 18:09:17.114,"208 km ENE of Sola, Vanuatu",Vanuatu,681.238,4.0
2,us7000kxdn,2023-09-18 15:35:27.270,Vanuatu region,Vanuatu region,675.265,4.2
3,us6000mivr,2024-03-08 22:42:23.713,Fiji region,Fiji region,671.043,4.2
4,us6000ta9m,2026-07-05 14:22:25.469,"265 km SE of Levuka, Fiji",Fiji,670.304,5.7
5,us6000rk66,2025-10-29 17:07:34.157,"205 km ESE of Levuka, Fiji",Fiji,669.556,4.8
6,us6000f2w3,2021-08-01 22:12:46.340,"283 km SE of Levuka, Fiji",Fiji,669.460,4.0
7,us7000q1jk,2025-05-10 02:03:16.756,"299 km E of Levuka, Fiji",Fiji,667.237,4.2
8,us7000s0st,2026-02-14 08:27:48.418,"205 km ESE of Levuka, Fiji",Fiji,667.197,4.3
9,us6000dhfx,2021-02-13 16:26:42.487,south of the Fiji Islands,south of the Fiji Islands,664.740,4.5

In [59]:
query = """
SELECT
    id,
    time,
    place,
    country,
    depth_km,
    mag
FROM earthquakes
WHERE depth_km < 50
  AND mag > 7.5
ORDER BY mag DESC;
"""

shallow_strong_eq = pd.read_sql(query, engine)

In [60]:
shallow_strong_eq

,id,time,place,country,depth_km,mag
0,us6000qw60,2025-07-29 23:24:52.483,"2025 Kamchatka Peninsula, Russia Earthquake",Russia Earthquake,35.000,8.8
1,ak0219neiszm,2021-07-29 06:15:49.188,"2021 Chignik, Alaska Earthquake",Alaska Earthquake,35.000,8.2
2,us6000f53e,2021-08-12 18:35:17.231,2021 South Sandwich Islands Earthquake,2021 South Sandwich Islands Earthquake,22.790,8.1
3,us7000dflf,2021-03-04 19:28:33.178,"2021 Kermadec Islands, New Zealand Earthquake",New Zealand Earthquake,28.930,8.1
4,us7000qx2g,2025-09-18 18:58:14.939,"140 km E of Petropavlovsk-Kamchatsky, Russia",Russia,27.000,7.8
5,us6000jllz,2023-02-06 01:17:34.342,"Pazarcik earthquake, Kahramanmaras earthquake ...",Kahramanmaras earthquake sequence,10.000,7.8
6,us6000dg77,2021-02-10 13:19:55.530,southeast of the Loyalty Islands,southeast of the Loyalty Islands,10.000,7.7
7,us7000pn9s,2025-03-28 06:20:52.715,"2025 Mandalay, Burma (Myanmar) Earthquake",Burma (Myanmar) Earthquake,10.000,7.7
8,us6000kd0n,2023-05-19 02:57:03.172,southeast of the Loyalty Islands,southeast of the Loyalty Islands,18.053,7.7
9,us6000rtdt,2025-12-08 14:15:09.896,"2025 Aomori Prefecture, Japan Earthquake",Japan Earthquake,40.720,7.6
10,us7000i9bw,2022-09-19 18:05:08.217,"35 km SSW of Aguililla, Mexico",Mexico,26.943,7.6
11,us7000lff4,2023-12-02 14:37:04.454,"19 km E of Gamut, Philippines",Philippines,40.000,7.6
12,us7000pcdl,2025-02-08 23:23:14.697,"210 km SSW of George Town, Cayman Islands",Cayman Islands,14.326,7.6
13,us6000rgf4,2025-10-10 20:29:20.075,Drake Passage,Drake Passage,5.639,7.6

In [61]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'mmi', 'alert', 'felt',
       'cdi', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms',
       'gap', 'type', 'country', 'year', 'month', 'day', 'day_of_week',
       'depth_category', 'strong_destructive_flag'],
      dtype='object')

In [62]:
query = """
SELECT
    country,
    AVG(depth_km) AS avg_depth_km
FROM earthquakes
GROUP BY country
ORDER BY avg_depth_km DESC;
"""

avg_depth_country = pd.read_sql(query, engine)

In [63]:
avg_depth_country

                                             country  avg_depth_km
0                          Peru-Brazil border region    605.390000
1                                        North Korea    577.230750
2                                        Fiji region    539.312636
3    eastern Russia-northeastern China border region    520.242000
4                                               Fiji    518.270054
..                                               ...           ...
526                                   North Carolina      0.100000
527                 Tennessee-Virginia border region      0.000000
528                                       Indonesia       0.000000
529                                             Iowa      0.000000
530                                        Minnesota      0.000000

[531 rows x 2 columns]

In [64]:
query = """
SELECT
    "magType",
    ROUND(AVG(mag)::numeric, 2) AS avg_magnitude,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY "magType"
ORDER BY avg_magnitude DESC;
"""

avg_magtype = pd.read_sql(query, engine)
avg_magtype

       magType  avg_magnitude  earthquake_count
0          mwc           6.15                 2
1        ms_20           5.80                 1
2          mwb           5.80                31
3          mww           5.37              7236
4          mwp           5.25                 1
5        ms_vx           4.60                 2
6           mb           4.42             83145
7          mwr           4.32              2775
8           mh           4.10                 1
9           mw           3.94               670
10         mlr           3.48                10
11         mlv           3.47                 5
12          md           3.44              6427
13  ml(texnet)           3.37                43
14         mlg           3.30                 1
15          ml           3.28             16899
16       mb_lg           3.20               125

In [65]:
query = """
SELECT
    year,
    COUNT(*) AS total_earthquakes
FROM earthquakes
GROUP BY year
ORDER BY total_earthquakes DESC
LIMIT 1;
"""

year_most_eq = pd.read_sql(query, engine)
year_most_eq

   year  total_earthquakes
0  2025              22818

In [66]:
query = """
SELECT
    month,
    COUNT(*) AS total_earthquakes
FROM earthquakes
GROUP BY month
ORDER BY total_earthquakes DESC
LIMIT 1;
"""

month_most_eq = pd.read_sql(query, engine)
month_most_eq

   month  total_earthquakes
0      7              11659

In [67]:
query = """
SELECT
    day_of_week,
    COUNT(*) AS total_earthquakes
FROM earthquakes
GROUP BY day_of_week
ORDER BY total_earthquakes DESC
LIMIT 1;
"""

day_most_eq = pd.read_sql(query, engine)
day_most_eq

  day_of_week  total_earthquakes
0      Friday              16971

In [68]:
query = """
SELECT
    DATE_PART('hour', CAST(time AS TIMESTAMP)) AS hour_of_day,
    COUNT(*) AS total_earthquakes
FROM earthquakes
GROUP BY hour_of_day
ORDER BY hour_of_day;
"""

hourly_eq = pd.read_sql(query, engine)
hourly_eq

    hour_of_day  total_earthquakes
0           0.0               4850
1           1.0               5144
2           2.0               4979
3           3.0               5199
4           4.0               5144
5           5.0               4818
6           6.0               4736
7           7.0               4873
8           8.0               4901
9           9.0               4846
10         10.0               4719
11         11.0               4619
12         12.0               4589
13         13.0               4841
14         14.0               4689
15         15.0               4835
16         16.0               4741
17         17.0               4878
18         18.0               4902
19         19.0               4958
20         20.0               4990
21         21.0               5191
22         22.0               5075
23         23.0               4857

In [69]:
query = """
SELECT
    net,
    COUNT(*) AS total_earthquakes
FROM earthquakes
GROUP BY net
ORDER BY total_earthquakes DESC
LIMIT 1;
"""

most_active_net = pd.read_sql(query, engine)
most_active_net

  net  total_earthquakes
0  us             102598

In [70]:
query = """
SELECT
    place,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY place
ORDER BY earthquake_count DESC
LIMIT 5;
"""

top_places = pd.read_sql(query, engine)
top_places

                              place  earthquake_count
0     South Sandwich Islands region              3178
1         south of the Fiji Islands              2045
2           Kermadec Islands region              1963
3                       Fiji region              1329
4  southeast of the Loyalty Islands              1096

In [71]:
query = """
SELECT
    alert,
    COUNT(*) AS earthquake_count,
    ROUND(AVG(mag)::numeric, 2) AS avg_magnitude
FROM earthquakes
GROUP BY alert
ORDER BY avg_magnitude DESC;
"""

alert_analysis = pd.read_sql(query, engine)
alert_analysis

    alert  earthquake_count  avg_magnitude
0     red                28           6.76
1  orange                25           6.32
2  yellow               138           6.01
3   green              4604           5.38
4    none            112579           4.21

In [72]:
query = """
SELECT
    status,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY status
ORDER BY earthquake_count DESC;
"""

status_count = pd.read_sql(query, engine)
status_count

      status  earthquake_count
0   reviewed            117207
1  automatic               167

In [73]:
query = """
SELECT
    type,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY type
ORDER BY earthquake_count DESC;
"""

type_count = pd.read_sql(query, engine)
type_count

                     type  earthquake_count
0              earthquake            116480
1        mining explosion               849
2               ice quake                13
3       volcanic eruption                12
4  experimental explosion                 5
5             other event                 5
6               landslide                 4
7           mine collapse                 3
8            quarry blast                 2
9               explosion                 1

In [74]:
query = """
SELECT
    types,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY types
ORDER BY earthquake_count DESC;
"""

types_count = pd.read_sql(query, engine)
types_count

                                                 types  earthquake_count
0                                  ,origin,phase-data,             89251
1                             ,dyfi,origin,phase-data,              8936
2                         ,origin,phase-data,shakemap,              2443
3                  ,earthquake-name,origin,phase-data,              2172
4                    ,moment-tensor,origin,phase-data,              1392
..                                                 ...               ...
570  ,dyfi,general-text,ground-failure,impact-text,...                 1
571  ,associate,dyfi,focal-mechanism,impact-link,lo...                 1
572  ,internal-moment-tensor,internal-origin,losspa...                 1
573  ,dyfi,general-text,ground-failure,impact-text,...                 1
574  ,associate,dyfi,general-text,ground-failure,im...                 1

[575 rows x 2 columns]

In [75]:
query = """
SELECT
    id,
    time,
    place,
    mag,
    nst
FROM earthquakes
WHERE nst > 100
ORDER BY nst DESC;
"""

high_station_events = pd.read_sql(query, engine)
high_station_events

,id,time,place,mag,nst
0,us6000m12f,2024-01-02 01:17:31.568,"11 km W of Anamizu, Japan",5.40,619.0
1,us6000qzfl,2025-08-09 08:01:41.017,"120 km ENE of Ozernovskiy, Russia",5.00,566.0
2,us7000rluk,2026-01-01 06:46:54.742,"111 km N of Yakutat, Alaska",5.70,516.0
3,us7000pvtr,2025-04-29 14:53:37.897,Macquarie Island region,6.80,475.0
4,usd001097k,2023-12-11 18:35:59.877,"49 km WNW of San Antonio de los Cobres, Argentina",5.50,466.0
...,...,...,...,...,...
7793,us6000pgw3,2025-01-01 15:26:08.391,"23 km WNW of Āwash, Ethiopia",4.80,101.0
7794,ok2022tcwv,2022-09-29 22:59:09.080,"2 km ESE of Aline, Oklahoma",3.09,101.0
7795,us6000inz1,2022-09-28 13:20:47.730,Reykjanes Ridge,4.60,101.0
7796,us6000inmh,2022-09-27 13:07:35.183,Reykjanes Ridge,4.70,101.0
7797,us6000t81q,2026-06-25 06:19:35.993,"75 km E of Kokopo, Papua New Guinea",5.50,101.0

In [76]:
query = """
SELECT
    year,
    COUNT(*) AS tsunami_count
FROM earthquakes
WHERE tsunami = 1
GROUP BY year
ORDER BY year;
"""

tsunami_per_year = pd.read_sql(query, engine)
tsunami_per_year

   year  tsunami_count
0  2021            114
1  2022            136
2  2023            119
3  2024            114
4  2025            142
5  2026             34

In [77]:
query = """
SELECT
    alert,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY alert
ORDER BY earthquake_count DESC;
"""

alert_count = pd.read_sql(query, engine)
alert_count

    alert  earthquake_count
0    none            112579
1   green              4604
2  yellow               138
3     red                28
4  orange                25

In [78]:
query = """
SELECT
    country,
    ROUND(AVG(mag)::numeric, 2) AS avg_magnitude,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY country
HAVING COUNT(*) > 0
ORDER BY avg_magnitude DESC
LIMIT 5;
"""

top5_countries = pd.read_sql(query, engine)
top5_countries

                                  country  avg_magnitude  earthquake_count
0                  New Zealand Earthquake           8.10                 1
1                       Russia Earthquake           8.10                 2
2  2021 South Sandwich Islands Earthquake           8.10                 1
3              Burma (Myanmar) Earthquake           7.70                 1
4       Kahramanmaras earthquake sequence           7.65                 2

In [79]:
query = """
SELECT
    country,
    year,
    month
FROM earthquakes
GROUP BY country, year, month
HAVING
    SUM(CASE WHEN depth_km < 70 THEN 1 ELSE 0 END) > 0
    AND
    SUM(CASE WHEN depth_km > 300 THEN 1 ELSE 0 END) > 0
ORDER BY country, year, month;
"""

result = pd.read_sql(query, engine)
result

               country  year  month
0          Afghanistan  2022     10
1            Argentina  2021      2
2            Argentina  2021      5
3            Argentina  2021      6
4            Argentina  2021     10
..                 ...   ...    ...
874  Wallis and Futuna  2025      7
875  Wallis and Futuna  2025      8
876  Wallis and Futuna  2025     12
877  Wallis and Futuna  2026      5
878  Wallis and Futuna  2026      6

[879 rows x 3 columns]

In [80]:
query = """
WITH yearly_counts AS (
    SELECT
        year,
        COUNT(*) AS total_earthquakes
    FROM earthquakes
    GROUP BY year
)
SELECT
    year,
    total_earthquakes,
    LAG(total_earthquakes) OVER (ORDER BY year) AS previous_year_count,
    ROUND(
        (
            (total_earthquakes - LAG(total_earthquakes) OVER (ORDER BY year))
            * 100.0
            / LAG(total_earthquakes) OVER (ORDER BY year)
        )::numeric,
        2
    ) AS yoy_growth_rate
FROM yearly_counts
ORDER BY year;
"""

yoy_growth = pd.read_sql(query, engine)
yoy_growth

   year  total_earthquakes  previous_year_count  yoy_growth_rate
0  2021              21926                  NaN              NaN
1  2022              20208              21926.0            -7.84
2  2023              20830              20208.0             3.08
3  2024              18659              20830.0           -10.42
4  2025              22818              18659.0            22.29
5  2026              12933              22818.0           -43.32

In [81]:
query = """
SELECT
    country,
    COUNT(*) AS earthquake_count,
    ROUND(AVG(mag)::numeric, 2) AS avg_magnitude,
    ROUND((COUNT(*) * AVG(mag))::numeric, 2) AS activity_score
FROM earthquakes
WHERE country IS NOT NULL
GROUP BY country
ORDER BY activity_score DESC
LIMIT 3;
"""

top_regions = pd.read_sql(query, engine)
top_regions

     country  earthquake_count  avg_magnitude  activity_score
0     Alaska             14501           3.47        50317.17
1  Indonesia              9000           4.50        40472.70
2     Russia              6371           4.48        28557.80

In [82]:
query = """
SELECT
    country,
    COUNT(*) AS earthquake_count,
    ROUND(AVG(depth_km)::numeric, 2) AS avg_depth_km
FROM earthquakes
WHERE latitude BETWEEN -5 AND 5
  AND country IS NOT NULL
GROUP BY country
ORDER BY avg_depth_km DESC;
"""

equator_depth = pd.read_sql(query, engine)
equator_depth

                                   country  earthquake_count  avg_depth_km
0                              Celebes Sea                11        452.79
1                                Banda Sea                11        339.38
2                              Philippines               595        110.98
3                             Bismarck Sea                 6        106.02
4                         Papua New Guinea              1198         71.75
5                                     Peru                95         64.86
6                                  Ecuador               314         62.74
7                                Indonesia              5935         62.23
8               Peru-Ecuador border region                 5         59.68
9                            northern Peru                 2         55.07
10                             Molucca Sea                72         51.64
11                                Colombia               128         43.17
12               near the coast of Ecuador                 3         30.97
13                            Palau region                 1         15.09
14                            Congo-Uganda                 1         14.78
15                off the coast of Ecuador                32         11.37
16                      South Indian Ocean                15         11.33
17                               Venezuela                 1         11.13
18                                Malaysia                 4         10.76
19  off the west coast of northern Sumatra                15         10.60
20                                  Brazil                 3         10.56
21                                  Rwanda                26         10.44
22                                  Guyana                 7         10.35
23        off the coast of Central America                69         10.26
24                         south of Panama                43         10.18
25                                  Uganda                25         10.08
26                         Carlsberg Ridge               150         10.04
27              central Mid-Atlantic Ridge               239         10.01
28                                Tanzania                39         10.00
29               Chagos Archipelago region                39         10.00
30        Galapagos Triple Junction region                38         10.00
31                      North Indian Ocean                 5         10.00
32                    South Atlantic Ocean                 2         10.00
33              east central Pacific Ocean                 6         10.00
34   Federated States of Micronesia region                 4         10.00
35               north of Ascension Island               117         10.00
36                                Ethiopia                 1         10.00
37                                  Panama                 1         10.00
38                             South Sudan                 2         10.00
39          Colombia-Ecuador border region                 1         10.00
40           west of the Galapagos Islands                28         10.00
41                                 Burundi                 6         10.00
42                         Kiribati region                 4         10.00
43                                   Palau                 6         10.00
44               central East Pacific Rise                75         10.00
45                          Ecuador region                16          9.99
46        Democratic Republic of the Congo                25          9.92
47                                   Kenya                 3          9.87
48                                   Gabon                11          9.82

In [83]:
query = """
SELECT
    country,
    SUM(CASE WHEN depth_km < 70 THEN 1 ELSE 0 END) AS shallow_count,
    SUM(CASE WHEN depth_km > 300 THEN 1 ELSE 0 END) AS deep_count,
    ROUND(
        (
            SUM(CASE WHEN depth_km < 70 THEN 1 ELSE 0 END)::numeric
            / NULLIF(SUM(CASE WHEN depth_km > 300 THEN 1 ELSE 0 END), 0)
        ),
        2
    ) AS shallow_deep_ratio
FROM earthquakes
WHERE country IS NOT NULL
GROUP BY country
HAVING SUM(CASE WHEN depth_km > 300 THEN 1 ELSE 0 END) > 0
ORDER BY shallow_deep_ratio DESC
LIMIT 10;
"""

ratio_df = pd.read_sql(query, engine)
ratio_df

,country,shallow_count,deep_count,shallow_deep_ratio
0,China,1449,1,1449.00
1,Peru,724,1,724.00
2,Guam,477,1,477.00
3,Afghanistan,260,1,260.00
4,New Zealand,1427,11,129.73
5,Solomon Islands,814,8,101.75
6,Russia,5426,102,53.20
7,south of the Kermadec Islands,680,17,40.00
8,Vanuatu,1175,31,37.90
9,Japan,4287,133,32.23

In [84]:
query = """
SELECT
    tsunami,
    ROUND(AVG(mag)::numeric, 2) AS avg_magnitude,
    COUNT(*) AS earthquake_count
FROM earthquakes
GROUP BY tsunami
ORDER BY tsunami DESC;
"""

tsunami_mag = pd.read_sql(query, engine)
tsunami_mag

   tsunami  avg_magnitude  earthquake_count
0        1           5.42               659
1        0           4.25            116715

In [85]:
query = """
SELECT
    id,
    time,
    place,
    mag,
    gap,
    rms,
    ROUND(((gap + rms) / 2.0)::numeric, 2) AS reliability_error_score
FROM earthquakes
WHERE gap IS NOT NULL
  AND rms IS NOT NULL
ORDER BY reliability_error_score DESC
LIMIT 10;
"""

low_reliability_events = pd.read_sql(query, engine)
low_reliability_events

,id,time,place,mag,gap,rms,reliability_error_score
0,pr71519528,2026-06-11 12:21:59.730,"95 km ENE of Cruz Bay, U.S. Virgin Islands",3.31,359.00,0.1400,179.57
1,nn00897599,2025-05-14 12:02:09.568,"60 km NE of Valmy, Nevada",3.00,358.18,0.1601,179.17
2,pr2024051000,2024-02-20 05:23:09.140,"77 km NW of Sandy Ground Village, Anguilla",3.58,358.00,0.1600,179.08
3,pr71508583,2026-02-23 19:35:44.000,"86 km WNW of Sandy Ground Village, Anguilla",3.17,356.00,0.2200,178.11
4,us7000denb,2021-02-14 19:26:12.202,"Andreanof Islands, Aleutian Islands, Alaska",3.30,355.00,0.3400,177.67
5,aka2026fwzivr,2026-03-25 08:04:49.491,south of Alaska,3.90,354.00,0.7000,177.35
6,pr2022227000,2022-08-15 01:27:45.500,"59 km ENE of Cruz Bay, U.S. Virgin Islands",3.63,353.00,0.6100,176.81
7,pr71489653,2025-07-18 23:19:06.230,"53 km SSW of Boca de Yuma, Dominican Republic",3.13,352.00,0.1800,176.09
8,pr2022289000,2022-10-16 20:43:51.670,"78 km E of Cruz Bay, U.S. Virgin Islands",3.48,352.00,0.0700,176.04
9,pr2021003002,2021-01-03 01:55:58.430,"87 km WNW of The Bottom, Bonaire, Saint Eustat...",3.53,351.00,0.4400,175.72

In [86]:
query = """
SELECT
    country,
    COUNT(*) AS deep_earthquake_count,
    ROUND(AVG(depth_km)::numeric, 2) AS avg_depth_km
FROM earthquakes
WHERE depth_km > 300
  AND country IS NOT NULL
GROUP BY country
ORDER BY deep_earthquake_count DESC
LIMIT 10;
"""

deep_focus_regions = pd.read_sql(query, engine)
deep_focus_regions

                     country  deep_earthquake_count  avg_depth_km
0  south of the Fiji Islands                   1719        522.81
1                Fiji region                   1282        556.76
2                       Fiji                   1227        565.86
3                      Tonga                    621        471.61
4                  Indonesia                    291        457.54
5               Japan region                    254        448.79
6                Timor Leste                    220        445.68
7          Wallis and Futuna                    167        407.72
8    Kermadec Islands region                    167        391.63
9                      Japan                    133        362.51

In [87]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.2.1)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.2.5)
Requirement already satisfied: packaging>=20 in c:\users\pearl\appdata\roaming\python\python312\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (12.2.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (7.35.1)
Requirement already satisfied: pyarrow>=7.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\pearl\appdata\roaming\python\python312\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: colorama in c:\users\pearl\appdata\roaming\python\python312\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in c:\users\pearl\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [88]:
import streamlit as st

In [89]:
st.set_page_config(
    page_title="Earthquake Analytics Dashboard",
    layout="wide"
)

st.title("Earthquake Data Analysis Dashboard")

2026-08-15 01:21:18.492 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:18.494 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:19.072
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\pearl\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-08-15 01:21:19.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:19.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [90]:
total_eq = pd.read_sql(
    "SELECT COUNT(*) total FROM earthquakes",
    engine
).iloc[0,0]

st.metric(
    "Total Earthquakes",
    f"{total_eq:,}"
)

2026-08-15 01:21:22.906 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:22.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:22.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [91]:
st.map(df[['latitude','longitude']])

2026-08-15 01:21:25.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:25.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:25.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [92]:
import plotly.express as px

fig = px.pie(
    df,
    names='alert'
)

st.plotly_chart(fig)

2026-08-15 01:21:27.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:27.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:27.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:27.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:27.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [93]:
page = st.sidebar.radio(
    "Navigation",
    [
        "Dashboard",
        "Query Analysis",
        "Map View"
    ]
)

2026-08-15 01:21:29.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:29.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:29.544 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:29.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:29.547 Session state does not function when running a script without `streamlit run`
2026-08-15 01:21:29.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:29.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-08-15 01:21:29.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.